apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo-pod
  labels:
    app: demo
spec:
  containers:
    - name: kubernetes-demo-container
      image: 880831ian/kubernetes-demo
      ports:
        - containerPort: 3000
