apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000 # 外部訪問 Port
      targetPort: 3000 # Pod內部 Port
  selector:
    app: demo
